builders:
  envy_generator:
    import: "package:envy_generator/builder.dart"
    builder_factories: ["envy"]
    build_extensions: { ".dart": [".e.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]