name: envy_generator
description: Code generation for extracting environment variables 
version: 0.0.4
homepage: https://github.com/ksokolovskyi/envy

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ">=5.0.0 <6.0.0"
  build: ^2.0.0
  dotenv: ^4.0.1
  envy_annotation: ^0.0.1
  recase: ^4.0.0
  source_gen: ^1.2.0

dev_dependencies:
  source_gen_test: ^1.0.2
  test: ^1.21.0
