name: Build

on: [push, pull_request]

jobs:
  envy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - envy_generator

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: dart format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Generate
        run: |
          if grep -q build_runner "pubspec.yaml"; then
            dart pub run build_runner build --delete-conflicting-outputs
          fi
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: dart analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: dart test
        working-directory: ${{ matrix.package }}